version: '3.7'

volumes:
  esdata:
    driver: local

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    volumes:
      - esdata:/usr/share/elasticsearch/data

networks:
  elastic:
    driver: bridge
